# Generated by Django 6.0 on 2026-02-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
